name: Java CI con Maven

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Grant execute permission to mvnw
        run: chmod +x ./mvnw

      - name: Build and run Unit Tests
        run: ./mvnw clean test

  security-scan:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Grant full permissions
        run: sudo chmod -R 777 .

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  docker-build:
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops-fehe-app:latest

  deploy-aws:
      name: Despliegue Continuo en AWS EC2
      needs: docker-build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: ${{ vars.AWS_REGION }}

        - name: Enviar compose a instancia
          run: |
            FILE_BASE64=$(base64 -w 0 docker-compose.yml)
            REMOTE_PATH="/home/ec2-user/docker-compose.yml"
            aws ssm send-command \
            --instance-ids "${{ vars.INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Copiando docker-compose al servidor" \
            --parameters "{\"commands\":[\"echo '$FILE_BASE64' | base64 -d > $REMOTE_PATH\"]}"

        - name: Enviar configuracion CloudWatch a instancia
          run: |
            FILE_BASE64=$(base64 -w 0 cwagent-config.json)
            REMOTE_PATH="/home/ec2-user/cwagent-config.json"
            aws ssm send-command \
              --instance-ids "${{ vars.INSTANCE_ID }}" \
              --document-name "AWS-RunShellScript" \
              --comment "Copiando json de CloudWatch al servidor" \
              --parameters "{\"commands\":[\"echo '$FILE_BASE64' | base64 -d > $REMOTE_PATH\"]}"

        - name: Run SSH Command
          id: ssh-command
          uses: leonowski/ec2-ssh-ghactions@v1
          with:
            username: ec2-user
            ec2_instance_id: ${{ vars.INSTANCE_ID }}
            region: ${{ vars.AWS_REGION }}
            command: |
              sudo dnf install -y docker
              sudo systemctl enable --now docker
              sudo mkdir -p /usr/libexec/docker/cli-plugins
              sudo curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-$(uname -m) -o /usr/libexec/docker/cli-plugins/docker-compose
              sudo chmod +x /usr/libexec/docker/cli-plugins/docker-compose
              
              sleep 15
              
              export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
              export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
              export AWS_SESSION_TOKEN="${{ secrets.AWS_SESSION_TOKEN }}"
              
              sudo -E docker compose -f /home/ec2-user/docker-compose.yml up -d --force-recreate