name: Java CI con Maven

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Grant execute permission to mvnw
        run: chmod +x ./mvnw

      - name: Build and run Unit Tests
        run: ./mvnw clean test

  security-scan:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Grant full permissions
        run: sudo chmod -R 777 .

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  docker-build:
    needs: security-scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t devops-fehe-app:latest .
  deploy:
    name: Despliegue Continuo en Entorno Simulado
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código fuente
        uses: actions/checkout@v4

      - name: Levantar el microservicio con Docker Compose
        run: docker compose up -d

      - name: Verificar el estado de los contenedores
        run: docker ps